/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ivanca19
 */


import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import java.text.*;
import java.awt.print.*;
import static java.util.Date.parse;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.print.Printer;
import javax.swing.JTextArea;


public class CarDealer extends javax.swing.JFrame {

    /**
     * Creates new form CarDealer
     */
    public CarDealer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldPostCode = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxMake = new javax.swing.JComboBox<>();
        jTextFieldCost = new javax.swing.JTextField();
        jComboBoxModel = new javax.swing.JComboBox<>();
        jComboBoxColor = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBoxOpts = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jTextFieldTax = new javax.swing.JTextField();
        jTextFieldGrandTotal = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButtonPurchace = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ayala Car Dealer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setText("ID:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Address:");

        jLabel6.setText("Postal Code:");

        jLabel7.setText("City:");

        jLabel8.setText("Down Payment (Do not Include \"$\"):");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLastName))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCity))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 540, 220));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 250, 360));

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jComboBoxMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make", "Honda", "Hyundai", "Kia", "Nissan", "Subaru", "Toyota" }));
        jComboBoxMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMakeActionPerformed(evt);
            }
        });

        jTextFieldCost.setEditable(false);

        jComboBoxModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model" }));
        jComboBoxModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelActionPerformed(evt);
            }
        });

        jComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color" }));
        jComboBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColorActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Standard");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Deluxe");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Premium");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jComboBoxOpts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available Models" }));

        jLabel9.setText("Sort By:");

        jButton1.setText("Sort");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jComboBoxOpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(18, 53, Short.MAX_VALUE)
                        .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jComboBoxOpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2)
                            .addComponent(jLabel9)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox3))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 540, 130));

        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel10.setText("SubTotal:");

        jLabel11.setText("Tax:");

        jLabel12.setText("Total:");

        jTextFieldSubTotal.setEditable(false);

        jTextFieldTax.setEditable(false);

        jTextFieldGrandTotal.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(51, 51, 51)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSubTotal)
                    .addComponent(jTextFieldTax)
                    .addComponent(jTextFieldGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 540, 130));

        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));

        jButtonPurchace.setText("Add To Purchace");
        jButtonPurchace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPurchaceActionPerformed(evt);
            }
        });

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPurchace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPurchace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 250, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String cos = jTextField7.getText();
        downP = Double.parseDouble(cos);
        totalPrice -= downP;
        try {
            JTextArea temp = new JTextArea();
            temp.append("ID: " + jTextFieldID.getText() + "\r\n");
            temp.append("Name: " + jTextFieldName.getText() + "\r\n");
            temp.append("Surname: " + jTextFieldLastName.getText() + "\r\n");
            temp.append("Address: " + jTextFieldAddress.getText() + " " + jTextFieldPostCode.getText() + 
                    ", " + jTextFieldCity.getText() + "\r\n");
            
            totalTax = totalPrice*0.07;
            totalPrice += totalTax;
            
            
            temp.append(jTextArea2.getText());
            temp.append("Tax: " + String.format("$%.2f", totalTax) + "\r\n");
            temp.append("Down Payment: $" + jTextField7.getText() + "\r\n");
            temp.append("Grand Total: " + String.format("$%.2f", totalPrice));
            temp.print();
            //jTextArea2.print();
        } catch (PrinterException ex) {
            Logger.getLogger(CarDealer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        totalPrice = 0.0;
        
        Receipt = "";
    
        downP = 0.0;
        
        totalTax = 0.0;
        
        JTextField cleartext = null;
        try{
            for(Component c:jPanel3.getComponents()) {
                if(c.getClass().toString().contains("javax.swing.JTextField")) {
                    cleartext = (JTextField)c;
                    cleartext.setText("");
                    jTextArea2.setText("");
                    jTextFieldCost.setText("");
                    jTextFieldSubTotal.setText("");
                    jTextFieldTax.setText("");
                    jTextFieldGrandTotal.setText("");

                    }
                }
            } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Do you want to Reset");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Customer exit = new Customer();

        try{
            exit.iExitSystem();
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Do you want to exit");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Cars ca = new Cars();
        jComboBoxColor.addItem(ca.getRed());
        jComboBoxColor.addItem(ca.getBlue());
        jComboBoxColor.addItem(ca.getBlack());
        jComboBoxColor.addItem(ca.getWhite());
        jComboBoxColor.addItem(ca.getGrey());
        jComboBoxColor.addItem(ca.getYellow());
        jComboBoxColor.addItem(ca.getGreen());
        
        for(int i = 0; i < litCar.getCarList().size(); i++) {
            jComboBoxOpts.addItem(litCar.getCarList().get(i).toString());
        }
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jComboBoxModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelActionPerformed
        
        Cars mod = new Cars();
        
        if(jComboBoxModel.getSelectedItem().equals("Accord")) {
            String car = String.format("$%.2f", mod.getpAccord());
            jTextFieldCost.setText(car);
            model = "Accord";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Civic")) {
            String car = String.format("$%.2f", mod.getpCivic());
            jTextFieldCost.setText(car);
            model = "Civic";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("CRV")) {
            String car = String.format("$%.2f", mod.getpCRV());
            jTextFieldCost.setText(car);
            model = "CRV";
        }
        
        
        
        if(jComboBoxModel.getSelectedItem().equals("Accent")) {
            String car = String.format("$%.2f", mod.getpAccent());
            jTextFieldCost.setText(car);
            model = "Accent";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Elantra")) {
            String car = String.format("$%.2f", mod.getpElantra());
            jTextFieldCost.setText(car);
            model = "Elantra";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("SantaFe")) {
            String car = String.format("$%.2f", mod.getpSantaFe());
            jTextFieldCost.setText(car);
            model = "SantaFe";
        }
        
        
        
        if(jComboBoxModel.getSelectedItem().equals("Forte")) {
            String car = String.format("$%.2f", mod.getpForte());
            jTextFieldCost.setText(car);
            model = "Forte";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Rio")) {
            String car = String.format("$%.2f", mod.getpRio());
            jTextFieldCost.setText(car);
            model = "Rio";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Soul")) {
            String car = String.format("$%.2f", mod.getpSoul());
            jTextFieldCost.setText(car);
            model = "Soul";
        }
        
        
        
        if(jComboBoxModel.getSelectedItem().equals("Altima")) {
            String car = String.format("$%.2f", mod.getpAltima());
            jTextFieldCost.setText(car);
            model = "Altima";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("GTR")) {
            String car = String.format("$%.2f", mod.getpGTR());
            jTextFieldCost.setText(car);
            model = "GTR";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Sentra")) {
            String car = String.format("$%.2f", mod.getpSentra());
            jTextFieldCost.setText(car);
            model = "Sentra";
        }
        
        
        
        if(jComboBoxModel.getSelectedItem().equals("Ascent")) {
            String car = String.format("$%.2f", mod.getpAscent());
            jTextFieldCost.setText(car);
            model = "Ascent";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("BRZ")) {
            String car = String.format("$%.2f", mod.getpBRZ());
            jTextFieldCost.setText(car);
            model = "BRZ";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Impreza")) {
            String car = String.format("$%.2f", mod.getpImpreza());
            jTextFieldCost.setText(car);
            model = "Impreza";
        }
        
        
        
        if(jComboBoxModel.getSelectedItem().equals("CHR")) {
            String car = String.format("$%.2f", mod.getpCHR());
            jTextFieldCost.setText(car);
            model = "CHR";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Camry")) {
            String car = String.format("$%.2f", mod.getpCamry());
            jTextFieldCost.setText(car);
            model = "Camry";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Corolla")) {
            String car = String.format("$%.2f", mod.getpCorolla());
            jTextFieldCost.setText(car);
            model = "Corolla";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Supra")) {
            String car = String.format("$%.2f", mod.getpSupra());
            jTextFieldCost.setText(car);
            model = "Supra";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("GR86")) {
            String car = String.format("$%.2f", mod.getpGR86());
            jTextFieldCost.setText(car);
            model = "GR86";
        }
        
        if(jComboBoxModel.getSelectedItem().equals("Prius")) {
            String car = String.format("$%.2f", mod.getpPrius());
            jTextFieldCost.setText(car);
            model = "Prius";
        }
    }//GEN-LAST:event_jComboBoxModelActionPerformed

    private void jComboBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColorActionPerformed
        if(jComboBoxColor.getSelectedItem().equals("Red")) {
            color = "Red";
        }
        if(jComboBoxColor.getSelectedItem().equals("Blue")) {
            color = "Blue";
        }
        if(jComboBoxColor.getSelectedItem().equals("Black")) {
            color = "Black";
        }
        if(jComboBoxColor.getSelectedItem().equals("White")) {
            color = "White";
        }
        if(jComboBoxColor.getSelectedItem().equals("Grey")) {
            color = "Grey";
        }
        if(jComboBoxColor.getSelectedItem().equals("Yellow")) {
            color = "Yellow";
        }
        if(jComboBoxColor.getSelectedItem().equals("Green")) {
            color = "Green";
        }
    }//GEN-LAST:event_jComboBoxColorActionPerformed

    private void jComboBoxMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMakeActionPerformed
        
        Cars ca = new Cars();
        if(jComboBoxMake.getSelectedItem().equals("Honda")) {
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            
            jTextFieldCost.setText("");
            make = "Honda";
            
            jComboBoxModel.addItem("Accord");
            jComboBoxModel.addItem("Civic");
            jComboBoxModel.addItem("CRV");
            
        }
        
        if(jComboBoxMake.getSelectedItem().equals("Hyundai")) {
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            
            jTextFieldCost.setText("");
            make = "Hyundai";
            
            jComboBoxModel.addItem("Accent");
            jComboBoxModel.addItem("Elantra");
            jComboBoxModel.addItem("SantaFe");
            
        }
        
        if(jComboBoxMake.getSelectedItem().equals("Kia")) {
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            
            jTextFieldCost.setText("");
            make = "Kia";
            
            jComboBoxModel.addItem("Forte");
            jComboBoxModel.addItem("Rio");
            jComboBoxModel.addItem("Soul");
            
        }
        
        
        if(jComboBoxMake.getSelectedItem().equals("Nissan")) {
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            
            jTextFieldCost.setText("");
            make = "Nissan";
            
            jComboBoxModel.addItem("Altima");
            jComboBoxModel.addItem("GTR");
            jComboBoxModel.addItem("Sentra");
            
        }
        
        if(jComboBoxMake.getSelectedItem().equals("Subaru")) {
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            
            jTextFieldCost.setText("");
            make = "Subaru";
            
            jComboBoxModel.addItem("Ascent");
            jComboBoxModel.addItem("BRZ");
            jComboBoxModel.addItem("Impreza");
            
        }
        
        if(jComboBoxMake.getSelectedItem().equals("Toyota")) {
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            for(int i = 1; i < jComboBoxModel.getItemCount(); i++){
                jComboBoxModel.removeItemAt(i);
            }
            
            jTextFieldCost.setText("");
            make = "Toyota";
            
            jComboBoxModel.addItem("CHR");
            jComboBoxModel.addItem("Camry");
            jComboBoxModel.addItem("Corolla");
            jComboBoxModel.addItem("Supra");
            jComboBoxModel.addItem("GR86");
            jComboBoxModel.addItem("Prius");
            
        }
        
    }                                    

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
    }//GEN-LAST:event_jComboBoxMakeActionPerformed

    private double totalPrice;
    private String Receipt = "";
    private String make = "";
    private String model = "";
    private double downP;
    private double totalTax;
    private String color;
    private String type;
    private static CarAvailable litCar;
    
    private void jButtonPurchaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPurchaceActionPerformed
        
        String cos = jTextFieldCost.getText().substring(1);
        double dCos = Double.parseDouble(cos);
        totalPrice += dCos;
        String car = String.format("$%.2f", dCos);
        jTextFieldSubTotal.setText(String.format("$%.2f", totalPrice));
        totalTax = totalPrice*0.07;
        totalPrice += totalTax;
        jTextFieldTax.setText(String.format("$%.2f", totalTax));
        jTextFieldGrandTotal.setText(String.format("$%.2f", totalPrice));
        
        
        //Receipt += 
        
        Receipt +=  color + " " + type + " " + make + " " + model + " " + car + "\r\n";
        
        jTextArea2.setText(Receipt);
//        
    }//GEN-LAST:event_jButtonPurchaceActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        type = "Standard";
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        type = "Deluxe";
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        type = "Premium";
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        litCar = new CarAvailable();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarDealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonPurchace;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBoxColor;
    private javax.swing.JComboBox<String> jComboBoxMake;
    private javax.swing.JComboBox<String> jComboBoxModel;
    private javax.swing.JComboBox<String> jComboBoxOpts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldGrandTotal;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPostCode;
    private javax.swing.JTextField jTextFieldSubTotal;
    private javax.swing.JTextField jTextFieldTax;
    // End of variables declaration//GEN-END:variables
}
